id: P2E28EEED
initial_creation_type: input
source_metadata:
  title: Geshe Langri Thangpa Series
  language: es
  description: 'Texts by the famous Kadampa geshe Langri Thangpa Dorje Senge (glang
    ri thang pa rdo rje seng ge, 1054–1123):'
  volume:
    8f9f6e05d2b6487b9ef81617f2f1047e:
      title: Eight Verses of Training the Mind
      parent: Mind Training
    bc542406ac084f7b87a9cbf1857dc3ad:
      title: The Sayings of Geshe Langri Tangpa
      parent: Mind Training
created_at: '2022-02-28T23:23:30.192659'
last_modified_at: '2022-02-28T23:23:30.192662'
